### ISSUE TITLE
Question of  the error "mvn package" referring to the issue #14

### ISSUE THREAD

**Issue by medicine-wave** [ncats/molvec#26]
> root@container-a129119e3c-5ce561d0:~/autodl-tmp/molvec# mvn package
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for gov.nih.ncats:molvec:jar:0.9.9-SNAPSHOT
[WARNING] 'build.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.apache.maven.plugins:maven-compiler-plugin @ line 186, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] 
[INFO] ------------------------< gov.nih.ncats:molvec >------------------------
[INFO] Building MolVec 0.9.9-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ molvec ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ molvec ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ molvec ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 42539 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.5.1:testCompile (default-testCompile) @ molvec ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ molvec ---
[INFO] Surefire report directory: /root/autodl-tmp/molvec/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running gov.nih.ncats.molvec.internal.algo.FragmentTest
Tests run: 16, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.409 sec
Running gov.nih.ncats.molvec.internal.algo.UtilTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
Running gov.nih.ncats.molvec.internal.algo.LineSegmentTest
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.423 sec
Running gov.nih.ncats.molvec.internal.algo.BranchNodeTest
null-C-H-3-N-Br-O
null-C-H-3-N-Br-(-)
null-C-H-3-I-O-Br-O
null-C-H-3-I-O-Br-(-)
null-C-H-3-1-O-Br-O
null-C-H-3-1-O-Br-(-)
Is linkable:true
-?(-C(-O),-C(-O),-C(-O)) as (CH2O)3
Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.019 sec
Running gov.nih.ncats.molvec.internal.algo.ChemicalTest
org.openscience.cdk.exception.CDKException: Cannot assign Kekulé structure without randomly creating radicals.
        at org.openscience.cdk.aromaticity.Kekulization.kekulize(Kekulization.java:101)
        at gov.nih.ncats.molwitch.cdk.CdkChemicalImpl.kekulize(CdkChemicalImpl.java:616)
        at gov.nih.ncats.molwitch.cdk.CdkChemicalImpl.prepareForBuild(CdkChemicalImpl.java:555)
        at gov.nih.ncats.molwitch.ChemicalBuilder.build(ChemicalBuilder.java:422)
        at gov.nih.ncats.molwitch.Chemical.createFromSmiles(Chemical.java:201)
        at gov.nih.ncats.molvec.internal.algo.ChemicalTest.testReadAromaticSmiles(ChemicalTest.java:15)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.486 sec
Running gov.nih.ncats.molvec.internal.algo.MoleculeTest
Tests run: 242, Failures: 2, Errors: 2, Skipped: 0, Time elapsed: 99.754 sec <<< FAILURE!
testAsByteArray[smallAntiAlias](gov.nih.ncats.molvec.internal.algo.MoleculeTest)  Time elapsed: 0.469 sec  <<< ERROR!
gov.nih.ncats.molvec.internal.algo.StructureImageExtractor$ImageTooSmallException
        at gov.nih.ncats.molvec.internal.algo.StructureImageExtractor.load(StructureImageExtractor.java:4026)
        at gov.nih.ncats.molvec.internal.algo.StructureImageExtractor.load(StructureImageExtractor.java:852)
        at gov.nih.ncats.molvec.internal.algo.StructureImageExtractor.<init>(StructureImageExtractor.java:354)
        at gov.nih.ncats.molvec.internal.algo.StructureImageExtractor.<init>(StructureImageExtractor.java:369)
        at gov.nih.ncats.molvec.Molvec.ocr(Molvec.java:85)
        at gov.nih.ncats.molvec.Molvec.ocr(Molvec.java:64)
        at gov.nih.ncats.molvec.internal.algo.MoleculeTest.testAsByteArray(MoleculeTest.java:127)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

testAsFile[smallAntiAlias](gov.nih.ncats.molvec.internal.algo.MoleculeTest)  Time elapsed: 0.357 sec  <<< ERROR!
gov.nih.ncats.molvec.internal.algo.StructureImageExtractor$ImageTooSmallException
        at gov.nih.ncats.molvec.internal.algo.StructureImageExtractor.load(StructureImageExtractor.java:4026)
        at gov.nih.ncats.molvec.internal.algo.StructureImageExtractor.load(StructureImageExtractor.java:868)
        at gov.nih.ncats.molvec.internal.algo.StructureImageExtractor.<init>(StructureImageExtractor.java:362)
        at gov.nih.ncats.molvec.internal.algo.MoleculeTest.testAsFile(MoleculeTest.java:104)
        at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

testAsByteArray[alphaPro](gov.nih.ncats.molvec.internal.algo.MoleculeTest)  Time elapsed: 0.213 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[XMGQYMWWDOXHJM]-UHFFFAOYSA-N> but was:<[OTMSDBZUPAUEDD]-UHFFFAOYSA-N>
        at org.junit.Assert.assertEquals(Assert.java:117)
        at org.junit.Assert.assertEquals(Assert.java:146)
        at gov.nih.ncats.molvec.internal.algo.MoleculeTest.lambda$data$131(MoleculeTest.java:5886)
        at gov.nih.ncats.molvec.internal.algo.MoleculeTest.testAsByteArray(MoleculeTest.java:148)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

testAsFile[alphaPro](gov.nih.ncats.molvec.internal.algo.MoleculeTest)  Time elapsed: 0.201 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[XMGQYMWWDOXHJM]-UHFFFAOYSA-N> but was:<[OTMSDBZUPAUEDD]-UHFFFAOYSA-N>
        at org.junit.Assert.assertEquals(Assert.java:117)
        at org.junit.Assert.assertEquals(Assert.java:146)
        at gov.nih.ncats.molvec.internal.algo.MoleculeTest.lambda$data$131(MoleculeTest.java:5886)
        at gov.nih.ncats.molvec.internal.algo.MoleculeTest.testAsFile(MoleculeTest.java:108)
        at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Running gov.nih.ncats.molvec.internal.util.GeomUtilTest
[Point2D.Double[0.0, 0.0], Point2D.Double[1.0, 0.0], Point2D.Double[0.0, 1.0]]
Tests run: 21, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.239 sec
Running gov.nih.ncats.molvec.Java11RegressionTest

  Molvec0109282222432D

 19 21  0  0  0  0  0  0  0  0999 V2000
   -2.1795    0.7867    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.1795    1.8066    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -3.0632    0.2708    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.2898   -0.7491    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.2898    0.2708    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.1795   -1.2571    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    2.1590   -0.9209    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.0618   -1.1976    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.4000   -1.2571    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.4859   -0.7491    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    2.5660   -0.0669    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.3871   -1.2571    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.3537   -1.6517    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.0618   -2.0222    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -3.0632   -0.7491    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.4000    0.7867    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.4000   -2.2809    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.3871   -2.0597    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.9664    2.2855    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2 19  1  0
  1  3  1  0
  1  5  2  0
 11 13  1  0
  3 15  2  0
  4  5  1  0
  4  6  2  0
 13 14  1  0
  4  9  1  0
  7  8  1  0
 13 18  1  0
 12 18  1  0
  8 14  1  0
  7 12  1  0
  7 11  1  0
  9 10  1  0
  6 15  1  0
  9 17  2  0
  5 16  1  0
 10 12  1  0
M  END
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.104 sec
Running gov.nih.ncats.molvec.MolvecTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.176 sec

Results :

Failed tests:   testAsByteArray[alphaPro](gov.nih.ncats.molvec.internal.algo.MoleculeTest): expected:<[XMGQYMWWDOXHJM]-UHFFFAOYSA-N> but was:<[OTMSDBZUPAUEDD]-UHFFFAOYSA-N>
  testAsFile[alphaPro](gov.nih.ncats.molvec.internal.algo.MoleculeTest): expected:<[XMGQYMWWDOXHJM]-UHFFFAOYSA-N> but was:<[OTMSDBZUPAUEDD]-UHFFFAOYSA-N>

Tests in error: 
  testAsByteArray[smallAntiAlias](gov.nih.ncats.molvec.internal.algo.MoleculeTest)
  testAsFile[smallAntiAlias](gov.nih.ncats.molvec.internal.algo.MoleculeTest)

Tests run: 310, Failures: 2, Errors: 2, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:49 min
[INFO] Finished at: 2022-09-28T22:43:51+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project molvec: There are test failures.
[ERROR] 
[ERROR] Please refer to /root/autodl-tmp/molvec/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by medicine-wave** [comment]
Resolved: just skip test phrase
