### ISSUE TITLE
Runtime exception on particular PNG file

### ISSUE THREAD

**Issue by jasondbiggs** [ncats/molvec#3]
If this PNG file is nonstandard in some way, let me know and I can bring it up to our image team. I created the image by taking one of the images in the test suite here and running our ColorConvert function to convert it to grayscale.

```
> java -jar molvec-0.9.5-jar-with-dependencies.jar -f /Users/jasonb/test123.png
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
	at gov.nih.ncats.molvec.image.Grayscale.grayscale(Grayscale.java:191)
	at gov.nih.ncats.molvec.image.Grayscale.createRaster(Grayscale.java:127)
	at gov.nih.ncats.molvec.image.Grayscale.setRaster(Grayscale.java:40)
	at gov.nih.ncats.molvec.image.Grayscale.<init>(Grayscale.java:32)
	at gov.nih.ncats.molvec.image.ImageUtil.decode(ImageUtil.java:93)
	at gov.nih.ncats.molvec.image.ImageUtil.grayscale(ImageUtil.java:160)
	at gov.nih.ncats.molvec.image.Bitmap.read(Bitmap.java:1467)
	at gov.nih.ncats.molvec.algo.StructureImageExtractor.load(StructureImageExtractor.java:865)
	at gov.nih.ncats.molvec.algo.StructureImageExtractor.<init>(StructureImageExtractor.java:362)
	at gov.nih.ncats.molvec.algo.StructureImageExtractor.<init>(StructureImageExtractor.java:372)
	at gov.nih.ncats.molvec.Molvec.ocr(Molvec.java:26)
	at gov.nih.ncats.molvec.Main.main(Main.java:151)
```

![test123](https://user-images.githubusercontent.com/16337306/68047824-3b8aba80-fcad-11e9-95d2-f52cafd9a8d8.png)

**Comment by dkatzel-ncats** [comment]
Thanks! I don't think we ever expected a file with 2 channels.

Keep 'em coming!

**Comment by dkatzel-ncats** [comment]
With a little bit of code tweaking to account for a 2 channel png with grayscale and alpha the image now gets turned into this picture below.  We lose the `Me`but that might be good enough.  What input file was this from our test set?  Thanks

<img width="272" alt="image" src="https://user-images.githubusercontent.com/23079822/68050785-4ac53480-fcbc-11e9-8f79-9b307446d61c.png">

**Comment by tylerperyea** [comment]
@dkatzel-ncats that's right actually. `Me` is just methyl, so this is the correct expansion.

**Comment by dkatzel-ncats** [comment]
The code fix has been pushed can you try to pull the latest changes (currently 0.9.6-SNAPSHOT) and give it a try?  I'll hold off pushing yet another update to maven central for a bit incase you find other issues ;)

**Comment by jasondbiggs** [comment]
> What input file was this from our test set? Thanks

I can't seem to find a match, so it's very likely I found the file by taking a screenshot snippet from a PDF and pasted it into Mathematica.  That would have given me an image with RGB color space, then I called ColorConvert to try and put it into grayscale.

I can confirm this is fixed now - thank you for the quick bug fixes!
